# These are supported funding model platforms
github: Hupyth   # nếu bạn bật GitHub Sponsors
patreon: yourPatreonID
ko_fi: yourKoFiID
custom: ["https://www.paypal.me/yourPayPalLink", "https://buymeacoffee.com/yourID"]
