name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'   # đổi nếu project bạn cần version khác

    # Bước 3: Cài dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Bước 4: Lint code (PEP8 check)
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings (for now)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Bước 5: Run tests (nếu có pytest)
    - name: Run tests
      run: |
        pip install pytest
        pytest || echo "⚠️ No tests found"
